sequenceDiagram
    participant browser
    participant server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa /contains json data and timestamp and runs JavaScript function
    activate server
    server-->>browser: HTTP status code 201: Created
    deactivate server
